### ISSUE TITLE
Lua bindings in Element.pkg refer to size_t, which tolua++ doesn't understand

### ISSUE THREAD

**Issue by Ident** [cegui/cegui#1000]
**[Original report](https://bitbucket.org/cegui/cegui/issue/1000) by Erik Ogenvik (Bitbucket: [erikogenvik](https://bitbucket.org/erikogenvik), GitHub: [erikogenvik](https://github.com/erikogenvik)).**

----------------------------------------

Element.pkg contains:

    Element* getChildElementAtIdx(size_t idx) const;
    size_t getChildCount() const;

Problem is that tolua++ doesn't understand size_t, and will treat it as a "userdata".
The fix is to replace with these lines instead:

    Element* getChildElementAtIdx(unsigned int idx) const;
    unsigned int getChildCount() const;

Not totally correct since size_t doesn't have to be unsigned int, but if the user is on a 64-bit system and have more than 4,294,967,296 child windows, they probably have other issues.

**Reproducibility:** always

**OS:** Linux, **OS build:** , **Platform:** AMD64

**Comment by niello** [comment]
Won't fix. It is perhaps better to try `sol3` which handles 64-bit integers than to change C++ core API to match Lua limitations. Now I'm in doubt that someone really has pain with this issue.
