### ISSUE TITLE
[Window.ccp]moveToFront and activate aren't discreet

### ISSUE THREAD

**Issue by Ident** [cegui/cegui#1001]
**[Original report](https://bitbucket.org/cegui/cegui/issue/1001) by Anonymous.**

----------------------------------------

**Automatic migration. Original reporter: "Woovie"**

moveToFront_impl sets the window as active when it moves, activate calls moveToFront as well. Each should only do their own work.

**Reproducibility:** always

**Additional information:** https://bitbucket.org/cegui/cegui/src/e6c28156951d1a3fcd92dc88736423a64c832584/cegui/src/Window.cpp?at=default

Line 735 to be removed
Several lines near line 830 to be removed to not activate the window, even though it was moved forward.

**Comment by niello** [comment]
I agree here that moveToFromt must not activate a window, algthough I think activate must bring the window to front. I will do the fix this way.
