### ISSUE TITLE
Wrong rendering of Framewindow in Rendereffects demo in D3D Renderers

### ISSUE THREAD

**Issue by Ident** [cegui/cegui#1009]
**[Original report](https://bitbucket.org/cegui/cegui/issue/1009) by Lukas Meindl (Bitbucket: [Ident8](https://bitbucket.org/Ident8), ).**

----------------------------------------

The wobbly window render effect sample works fine with OGL. However in D3D the framewindow seems to be horizontally reduced by a certain amount. This is visible by looking at the framewindows title which is horizontally compressed. Also, when trying to grab the edges, they are either not grabbable (because the visual representation doesnt correspond with the actualy dimensions of the window) or grabbing them will make the window render correctly in 1 dimension for a moment.

**Reproducibility:** always

**Steps to reproduce:** Start the Rendereffects demo in a D3D renderer and try to resize the anti-aliasing window

**Comment by niello** [comment]
Checked, only Elastic effect has a described bug, both wobbly effects work well.

**Comment by niello** [comment]
The problem seems to be in the rendering window using the whole size of the RT, not the size of the window. So growing the window works well but shrinking its size leads to a proportional offset. Will try to fix.
