### ISSUE TITLE
interpolateRelativeMultiply only works for interpolating floats

### ISSUE THREAD

**Issue by Ident** [cegui/cegui#1036]
**[Original report](https://bitbucket.org/cegui/cegui/issue/1036) by Nick Enstein (Bitbucket: [Nickenstein79](https://bitbucket.org/Nickenstein79), GitHub: [Nickenstein79](https://github.com/Nickenstein79)).**

----------------------------------------

The interpolateRelativeMultiply method inside the TplLinearInterpolator template class only works for interpolating floats.

Passing higher types (such as UDim for animating a window's size/position with relative-multiply animation), will cause the value to be statically cast to a float, and hence result is garbage data and the object's properties get set to some nonsense value.

**Reproducibility:** always

**Steps to reproduce:** Animate some UDim property of a widgets (such as a button's size) using the Relative-Multiply technique.

Observe that the size property of the window gets set to {{0,0}, {0,0}} because of the problem described above.

**OS:** All, **OS build:** All, **Platform:** All

**Comment by niello** [comment]
This looks fixed in the master. Only float keyframes make sense in interpolateRelativeMultiply, and the base type is correct.
