### ISSUE TITLE
Compilation docu is lacking at least for Windows

### ISSUE THREAD

**Issue by Ident** [cegui/cegui#1046]
**[Original report](https://bitbucket.org/cegui/cegui/issue/1046) by Lukas Meindl (Bitbucket: [Ident8](https://bitbucket.org/Ident8), ).**

----------------------------------------

See http://cegui.org.uk/forum/posting.php?mode=reply&f=10&t=6828

**Reproducibility:** always

**Comment by niello** [comment]
Building with CMake is straightforward now. Not sure [](https://github.com/cegui/cegui#building-cegui) is helpful, may rewrite it later, but I know no gotchas to be documented immediately. An issue is 7 years old, let's wait for someone other complaining on the building process for Windows.
