### ISSUE TITLE
Flaky tooltip visibility when mousing between two tooltip windows

### ISSUE THREAD

**Issue by Ident** [cegui/cegui#1064]
**[Original report](https://bitbucket.org/cegui/cegui/issue/1064) by Sean Lindskog (Bitbucket: [slindskog](https://bitbucket.org/slindskog), GitHub: [slindskog](https://github.com/slindskog)).**

----------------------------------------

Repro:

 * run a CEGUI layout with 2 windows (buttons, StaticText, whatever)
 * both windows have a tooltip enabled
 * put the mouse over window 1
 * tooltip appears, as expected
 * quickly move the mouse over window 2
 * tooltip blinks visible for a brief moment, then disappears (bug)

I believe this problem is caused by the FadeOut animation defined on the tooltip in TaharezLook.looknfeel (or OgreTray.looknfeel).  If you move the mouse to a new window before the animation has completed, the tooltip appears, but then the animation sets the tooltip to hidden, causing it to erroneously blink out.

For reference, here is the FadeOut animation for the tooltip in TaharezLook.looknfeel:
Note the "Visible" affector.

```
#!xml

        <AnimationDefinition name="FadeOut" duration="0.33" replayMode="once">
            <Affector property="Alpha" interpolator="float">
                <KeyFrame position="0" sourceProperty="Alpha" />
                <KeyFrame position="0.33" value="0" progression="linear" />
            </Affector>
            <Affector property="Visible" interpolator="bool">
                <KeyFrame position="0" sourceProperty="Visible" />
                <KeyFrame position="0.33" value="false" progression="discrete" />
            </Affector>
            
            <Subscription event="TooltipInactive" action="Start" />
        </AnimationDefinition>



```

I assigned this as "major" only because my UI (and I imagine some other people's) rely on tooltips to give extra information about an item icon, a skill icon, or whatever.  If the tooltips don't behave, the UI is unacceptably broken.

**Comment by niello** [comment]
Not reproduced in master
