### ISSUE TITLE
Animated rotation going into the wrong direction in default branch

### ISSUE THREAD

**Issue by Ident** [cegui/cegui#1070]
**[Original report](https://bitbucket.org/cegui/cegui/issue/1070) by Lukas Meindl (Bitbucket: [Ident8](https://bitbucket.org/Ident8), ).**

----------------------------------------

Rotation goes wrong in default branch. **Regular rotations (non-animated) work fine - tested around each of the 3 axises!**

**Reproduction steps:** 

Add to a Samplebrowser demo (e.g. helloworld) and start, this rotates right in the 0.8.X versions but left in the default branch:
```
#!c++
    CEGUI::Animation* anim = AnimationManager::getSingleton().createAnimation("RightForSure");
    anim->setReplayMode(Animation::RM_Loop);
    anim->setDuration(0.8f);

    CEGUI::Affector* aff = anim->createAffector("Rotation", "QuaternionSlerp");
    aff->setApplicationMethod(Affector::AM_Absolute);

    aff->createKeyFrame(0.f, "x:0 y:0 z:0");
    aff->createKeyFrame(0.4f, "x:0 y:0 z:180");
    aff->createKeyFrame(0.8f, "x:0 y:0 z:360");

    

    CEGUI::AnimationInstance* instance = CEGUI::AnimationManager::getSingleton().instantiateAnimation(anim);
    instance->setTargetWindow(wnd);

    instance->start();

```

**Comment by niello** [comment]
@Ident , as you stated that only animated rotations are broken I assume the problem not in rotation math but in Euler to quat conversion. So I negated xyz on load and now rotations seem to have the desired direction. Tested as suggested in an issue and in a GameMenuSample.
