### ISSUE TITLE
Add support for min and max to <OperatorDim> falagard element

### ISSUE THREAD

**Issue by Ident** [cegui/cegui#1088]
**[Original report](https://bitbucket.org/cegui/cegui/issue/1088) by Christopher Beck (Bitbucket: [cbeck88](https://bitbucket.org/cbeck88), GitHub: [cbeck88](https://github.com/cbeck88)).**

----------------------------------------

Title says it all. This would be handy if I'm trying to make a widget that represents a pair of an image and some text, maybe located to the side. If I have a max operator then I can define it's height as the maximum of the text and the image.

I guess that it requires adding more stuff to this enum:
http://static.cegui.org.uk/docs/0.8.1/namespaceCEGUI.html#a83eeabd743af4692fae93272f0e3be72

**Comment by niello** [comment]
DimensionOperator already contains Min and Max
