### ISSUE TITLE
Throw a warning in CMake when only Release or Debug but not both dependencies are available

### ISSUE THREAD

**Issue by Ident** [cegui/cegui#1094]
**[Original report](https://bitbucket.org/cegui/cegui/issue/1094) by Lukas Meindl (Bitbucket: [Ident8](https://bitbucket.org/Ident8), ).**

----------------------------------------

See https://bitbucket.org/cegui/cegui/pull-request/161/fixed-static-build-dependency-build-for/diff for more information

**Comment by niello** [comment]
The link is broken and the issue is too old. I will close it and wait for the next encounter.
