### ISSUE TITLE
Silence "Package NOT found" message in CMake by default, add flag to switch it on for debugging

### ISSUE THREAD

**Issue by Ident** [cegui/cegui#1099]
**[Original report](https://bitbucket.org/cegui/cegui/issue/1099) by Lukas Meindl (Bitbucket: [Ident8](https://bitbucket.org/Ident8), ).**

----------------------------------------

CMake beginners using CEGUI seem to be confused about the "X NOT found" messages in the CMake log. Therefore, I suggest to silence all those messages if a Cmake option, e.g. "REPORT_MISSING_PACKAGES", is set to True, which should be its default state. 

This can be implemented easily based on the QUIET option in cmake: http://www.cmake.org/cmake/help/v3.0/command/find_package.html

Furthermore we should probably make use of the REQUIRED option for GLM

**Comment by niello** [comment]
GLM is already REQUIRED. CMake was cleaned up a lot in the recent time. Now I don't see the need for things described here, at least until users start asking this.
