### ISSUE TITLE
compilation errors with CEGUI static

### ISSUE THREAD

**Issue by Ident** [cegui/cegui#1112]
**[Original report](https://bitbucket.org/cegui/cegui/issue/1112) by Christopher Beck (Bitbucket: [cbeck88](https://bitbucket.org/cbeck88), GitHub: [cbeck88](https://github.com/cbeck88)).**

----------------------------------------

When compiling CEGUI v0-8 using the CEGUI_STATIC define to statically link everything, I get compilation errors related to the "CEGUI::FactoryModule" system.

```
#!c++

lib/cegui-0.8.4/src/FactoryModule.cpp:94:27: error: 'getWindowFactoryModule' has C-linkage specified, but returns user-defined type 'CEGUI::FactoryModule &' which is incompatible with C [-Werror,-Wreturn-type-c-linkage]
    CEGUI::FactoryModule& getWindowFactoryModule()
                          ^
1 error generated.

```

I think the error is exactly right -- how can you put a function that returns a reference inside an `extern "C"` block, since references are not part of C?

It looks to me like the `CEGUI_STATIC` option is possibly not being tested or used right now -- is it deprecated? I can post a patch with the changes I needed to fix it in my build system, but let me know if there's no point to that.

(I fixed these issues once many moons ago but I nuked my in-tree cegui copy and updated it with current v0-8 just now, because I wanted yaronCT's epoxy patch, so now I had to revisit all such issues.)

**Comment by niello** [comment]
I was able to build 0.8.7 statically, and it works for `master`
