### ISSUE TITLE
Poor performance of the new layout container

### ISSUE THREAD

**Issue by Ident** [cegui/cegui#1129]
**[Original report](https://bitbucket.org/cegui/cegui/issue/1129) by Victor P. R. Müller (Bitbucket: [Victor P. R. Müller](https://bitbucket.org/Victor P. R. Müller), ).**

----------------------------------------

The user called **funbiscuit** wanted to open this ticket. Because he didn't I'm opening it.
I'm reporting the experience of this user. 
The performance of the layout container the user self commited seems to be not well during resizing it. I do not know any futher things so please ask him for any further questions. 

Here is the link to the thread which specifies which container and which problem occured:
http://cegui.org.uk/forum/viewtopic.php?f=10&t=7190&hilit=performance

**Comment by niello** [comment]
LCs were rewritten and now I see no performance issues
