### ISSUE TITLE
FrameWindow Titlebar uses wrong font to calculate size

### ISSUE THREAD

**Issue by Ident** [cegui/cegui#1138]
**[Original report](https://bitbucket.org/cegui/cegui/issue/1138) by Henri Hyyryläinen (Bitbucket: [Henri Hyyryläinen](https://bitbucket.org/Henri Hyyryläinen), ).**

----------------------------------------

In the default branch (specific commit: `869014de5669`) FrameWindow's titlebars are too tall. They seem to be calculated with the default font, but when rendering they have the correct font.

http://imgur.com/a/EMuEP 
The top image is how it looks with the custom font and the bottom image is how it looks with the default font. See how both titlebars have the same height and it looks like the height is right on the bottom one.

Ident thought that this might be an issue with using some other font than the final display font to calculate the height of the titlebar.

**Comment by niello** [comment]
AFAIR I've fixed this. At least now titlebars look good.
