### ISSUE TITLE
CMake Deprecation Warning at CMakeLists.txt:6 (cmake_policy)

### ISSUE THREAD

**Issue by Ident** [cegui/cegui#1150]
**[Original report](https://bitbucket.org/cegui/cegui/issue/1150) by Bohdan Kornienko (Bitbucket: [Bohdan Kornienko](https://bitbucket.org/Bohdan Kornienko), ).**

----------------------------------------

During the generation of the Cmake project I am encountering the following warning message:

CMake Deprecation Warning at CMakeLists.txt:6 (cmake_policy):
  The OLD behavior for policy CMP0017 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

**Comment by niello** [comment]
Fixed in master
