### ISSUE TITLE
Add support for pugixml in 1.0, abandon rapidxml support in 1.0

### ISSUE THREAD

**Issue by Ident** [cegui/cegui#1151]
**[Original report](https://bitbucket.org/cegui/cegui/issue/1151) by Lukas Meindl (Bitbucket: [Ident8](https://bitbucket.org/Ident8), ).**

----------------------------------------

Rapidxml has not seen a Release in more than 4 years and is looking pretty much abandoned these days. This view is reinforced by the fact that there is no official public repository available to observe any progress in and by that there have been no news from the developer in those years.

Therefore, I strongly suggest abandoning our support for rapidxml starting with CEGUI 1.0 (of course keeping 0.8.X support for it) and "replacing" this "fastest xml parser" library by from then on supporting the pugixml parser, which makes similar claims abou speed, even claiming to exceed it at that:
https://pugixml.org/docs/manual.html

This library is still being updated and seems healthy:
https://github.com/zeux/pugixml

**Comment by niello** [comment]
Done
