### ISSUE TITLE
clearlinux build failed

### ISSUE THREAD

**Issue by Ident** [cegui/cegui#1156]
**[Original report](https://bitbucket.org/cegui/cegui/issue/1156) by Utku Helvacı (Bitbucket: [tuxutku](https://bitbucket.org/tuxutku), GitHub: [tuxutku](https://github.com/tuxutku)).**

----------------------------------------

**Operating System:** Linux clr-449e9b2a44f8458bb4885604dc172a1c 4.13.12-430.native #2 SMP Thu Nov 9 14:13:59 UTC 2017 x86_64 GNU/Linux (64-bit)        **OS version/build:** X
(Only for rendering-related issues:) **GPU:** X        **GPU driver:** X

In this section write a description of the issue including all relevant
logs, error messages, callstacks, code samples and links that could
be helpful in resolving the issue.

**Reproducibility:** (doesn't apply/always/never/sometimes)
tested only on my computer, it happens everytime
**Reproduction steps:** 

1. downloaded cegui-0.8.7

output of make is in attached file

**Comment by niello** [comment]
This is too old and there is no enough info to reproduce the bug. Please open a new ticket with more info if it is still actual.
