### ISSUE TITLE
CEGUI configured without PCRE will throw exception if loading a widget using regexes

### ISSUE THREAD

**Issue by Ident** [cegui/cegui#1158]
**[Original report](https://bitbucket.org/cegui/cegui/issue/1158) by Lukas Meindl (Bitbucket: [Ident8](https://bitbucket.org/Ident8), ).**

----------------------------------------

See thread: http://cegui.org.uk/forum/viewtopic.php?f=10&t=7346

If CEGUI has no PCRE then it will crash if loading a widget that actually can use and have defined a regex matching, such as spinners, editboxes etc.

Expected behaviour: should just throw a more explicit exception or PCRE should be mandatory or should silently fail.

**Comment by niello** [comment]
Fixed in master, won't fix in 0.8
