### ISSUE TITLE
Convert to Git repository to attract more developers.

### ISSUE THREAD

**Issue by Ident** [cegui/cegui#1162]
**[Original report](https://bitbucket.org/cegui/cegui/issue/1162) by Manh Nguyen Tien (Bitbucket: [manhnt9](https://bitbucket.org/manhnt9), GitHub: [manhnt9](https://github.com/manhnt9)).**

----------------------------------------

It's very easy to convert our repo from Mecurial to Git according to this tutorial: https://bitbucket.org/blog/converting-hg-repositories-to-git

Please consider it to help the development become easier for developers.
They won't have to learn hg comands or install GitHG (also introduces new commands).

I also propose this with Irrlicht team and they agreed to convert to git after Irrlicht 1.0's release.
Most of open-source projects are on github right now. We don't need to move to github but at least git seems to be the most popular version control besides svn.

**Comment by FluXy** [comment]
This can be closed now ;)

**Comment by Ident** [comment]
True true ;)
