### ISSUE TITLE
Cursor keeps moving in a sample browser

### ISSUE THREAD

**Issue by Ident** [cegui/cegui#1167]
**[Original report](https://bitbucket.org/cegui/cegui/issue/1167) by Vladimir Orlov (Bitbucket: [Jahndal](https://bitbucket.org/Jahndal), ).**

----------------------------------------

**Operating System:** Windows 8.1 (6-bit)
**Compiler:** MSVC 2017 v15.9.11

If sample browser is built in Release configuration then mouse cursor keeps moving after you stop moving the mouse.

**Reproducibility:** always in Release, never in Debug

**Comment by niello** [comment]
Fixed yesterday. The problem is in GLFW2. It updates a cursor position incorrectly when the system cursor is hidden.
