### ISSUE TITLE
List of sample browser bugs

### ISSUE THREAD

**Issue by Ident** [cegui/cegui#1168]
**[Original report](https://bitbucket.org/cegui/cegui/issue/1168) by Vladimir Orlov (Bitbucket: [Jahndal](https://bitbucket.org/Jahndal), ).**

----------------------------------------

= WidgetsSample =

MultiLineEditbox sets text from MultiLineEditbox::onTextChanged to add \n, effectively doing setText twice. Quite wasteful.
Scrollbars ignore click on bar & have one step for buttons
Scrollbar thumbs can be dragged outside the preview rect and lost until restart
*/MultiColumnList ping text is not colored
*/ImageButton not visible
*/Combobox - if text manually changed from existing to new, opened list shows previous existing text as selected
Generic/Image not visible
OgreTray/ComboDropList, Combobox, DropDownMenu crash "There is no WindowRendererFactory named 'Core/ListWidget' available"
OgreTray/ListHeader not visible
OgreTray/ListHeaderSegment not visible
OgreTray/ListboxItem not visible
OgreTray/Menubar not visible
OgreTray/PopupMenu not visible
TaharezLook/ComboDropList not visible
TaharezLook/InventoryItem not visible
TaharezLook/ListHeader not visible
TaharezLook/PopupMenu not visible
TaharezLook/SliderThumb not visible
Vanilla/ComboDropList not visible
WindowsLook/ComboDropList not visible
WindowsLook/IconButton not visible
WindowsLook/ListHeader not visible
WindowsLook/ListHeaderSegment not visible
WindowsLook/ListboxItem not visible
WindowsLook/MenuItem not visible
WindowsLook/MultiColumnList non-selected item text is white or not rendered at all
WindowsLook/PopupMenu not visible
WindowsLook/Slider has thumb only and is not functional
WindowsLook/SliderThumb not visible
WindowsLook/SystemButton not visible

= FontsSample =

Caret is too wide and causes the text to move

New font bug:
1. Select the last preset
2. Add new font mizufalp 12.0
3. Select it
4. Crash into FreeTypeFontGlyph::getRenderedAdvance(): CEGUI::FontGlyph::getImage(...) returned nullptr

= CustomShapesDrawingSample =

Left widget doesn't render FPS line

= Demo6Sample =

'Quit this demo' button doesn't work

= ModelViewSample =

Add random item in list - crash (ListViewItemRenderedString::setStringAndFormatting) if items exist, nothing if model is empty
Add random item (to root) - the same
Remove selected list item(s) - the same (or ListViewItemRenderedString::~ListViewItemRenderedString in tree) when at least one selected
Update selected list item's name - removes item from list & removes with gap in tree when the name is empty
Enable multiselection - Select multiple - Disable multiselection - Multuple items remain selected

= ScrollablePaneDemo =

No hotkey to create windows
File->Quit button in menu doesn't work

**Comment by niello** [comment]
Most of things here are fixed or outdated
