### ISSUE TITLE
Window clipping not working in Ogre 2.1 renderer

### ISSUE THREAD

**Issue by Ident** [cegui/cegui#1171]
**[Original report](https://bitbucket.org/cegui/cegui/issue/1171) by Robert Paciorek (Bitbucket: [RPaciorek](https://bitbucket.org/RPaciorek), GitHub: [RPaciorek](https://github.com/RPaciorek)).**

----------------------------------------

Clipping by parent don’t work on Ogre 3D module:

![](https://bitbucket.org/repo/jgqe6R/images/2774463496-ScrollablePane-Demo2.png)
‌

* Don’t work with static and frame window too \(not only ScrollablePane\)
* Is specific to Ogre Renderer \(clipping works OK on OpenGL rendering module\)
* `OgreGeometryBuffer::setScissorRects()` is called with correct values
* Looks like something wrong with enabling scissor test.

‌

_Ogre version_: **2.1**, tested hg version `a8abc76` and `12a6037` \(last\)

_Ogre Render System:_ **GL3Plus**

**Comment by ronaldta** [comment]
please see following pull request:
[https://github.com/cegui/cegui/pull/1206](url)
Unfortunatly i don't know how to link it to this issue.

**Comment by rpaciorek** [comment]
#1208 fix this issue. Thanks!

Sorry for the late reply – after migration to github notifications have turned off.
