### ISSUE TITLE
Rotation is not applied anymore when loading from XML

### ISSUE THREAD

**Issue by FluXy** [cegui/cegui#1176]
"[E] Window::setRotation - Failed to obtain a suitable ReneringWindow surface for Window 'newsticker_group'.  Rotation will not be available."

- Must have been one of the changes in the last ~8months. Probably the contextless/no_default_context changes.
- Seems to fail as the the parent window is not set before Element::setRotation() -> Window::onRotated() (so that Window::getTargetRenderingSurface() works). Parent window can not be set with WindowManager::loadLayoutFromFile() :D

allocateRenderingWindow() fails here:

>	CEGUI::Window::allocateRenderingWindow(bool addStencilBuffer) Line 3523
 	CEGUI::Window::setUsingAutoRenderingSurface(bool setting) Line 3485
 	CEGUI::Window::onRotated(CEGUI::ElementEventArgs & e) Line 3653
 	CEGUI::Element::setRotation(const glm::qua<float,0> & rotation) Line 565
 	CEGUI::TplWindowProperty<CEGUI::Element,glm::qua<float,0>>::setNative_impl(CEGUI::PropertyReceiver * receiver, const glm::qua<float,0> & value) Line 61
 	CEGUI::TypedProperty<glm::qua<float,0>>::setNative(CEGUI::PropertyReceiver * receiver, const glm::qua<float,0> & value) Line 84
 	CEGUI::TypedProperty<glm::qua<float,0>>::set(CEGUI::PropertyReceiver * receiver, const CEGUI::String & value) Line 73
 	CEGUI::PropertySet::setProperty(const CEGUI::String & name, const CEGUI::String & value) Line 141
 	CEGUI::GUILayout_xmlHandler::elementPropertyStart(const CEGUI::XMLAttributes & attributes) Line 368
 	CEGUI::GUILayout_xmlHandler::elementStart(const CEGUI::String & element, const CEGUI::XMLAttributes & attributes) Line 88
 	CEGUI::TinyXML2Parser::processElement(CEGUI::XMLHandler & handler, const tinyxml2::XMLElement * element) Line 79
 	CEGUI::TinyXML2Parser::processElement(CEGUI::XMLHandler & handler, const tinyxml2::XMLElement * element) Line 91
 	CEGUI::TinyXML2Parser::processElement(CEGUI::XMLHandler & handler, const tinyxml2::XMLElement * element) Line 91
 	CEGUI::TinyXML2Parser::processElement(CEGUI::XMLHandler & handler, const tinyxml2::XMLElement * element) Line 91
 	CEGUI::TinyXML2Parser::processElement(CEGUI::XMLHandler & handler, const tinyxml2::XMLElement * element) Line 91
 	CEGUI::TinyXML2Parser::parseXML(CEGUI::XMLHandler & handler, const CEGUI::RawDataContainer & source, const CEGUI::String & __formal, bool __formal) Line 64
 	CEGUI::XMLParser::parseXMLFile(CEGUI::XMLHandler & handler, const CEGUI::String & filename, const CEGUI::String & schemaName, const CEGUI::String & resourceGroup, bool allowXmlValidation) Line 68
 	CEGUI::WindowManager::loadLayoutFromFile(const CEGUI::String & filename, const CEGUI::String & resourceGroup, bool(*)(CEGUI::Window *, CEGUI::String &, CEGUI::String &, void *) callback, void * userdata) Line 287

**Comment by Ident** [comment]
Any idea how to fix it?
