### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by acxz** [cegui/cegui#1184]
It has been ~4 years since the last release. Is there a plan for a new release, if so when?

**Comment by Ident** [comment]
yes,  there will be one whenever a new release is ready. There is a lot to do to get a meaningful new version out (1.0 preferrably) and we are not there yet and we have too few active developers atm. Maybe if you and others help out we can make a new one. There are a lot of goals we should achieve for a 1.0 version, some are on the wiki (a bit hidden but i can link you there) and some are general, like making the samples more approachable, (application templates are great for that already), streamlining the interfaces, rewriting the docu for a better usability of the library and easier onboarding, architectural improvements, performance improvements, vulkan renderer,...

**Comment by acxz** [comment]
whoa that does sound like a lot, I'm afraid my time is limited, but I can help out in fixing compilation issues.

Keep up the great work!

**Comment by bbilas** [comment]
> Maybe if you and others help out we can make a new one. There are a lot of goals we should achieve for a 1.0 version, some are on the wiki (a bit hidden but i can link you there) and some are general, like making the samples more approachable, (application templates are great for that already), streamlining the interfaces, rewriting the docu for a better usability of the library and easier onboarding, architectural improvements, performance improvements, vulkan renderer,...

Share it with everyone and then we'll try to start further development ;)

**Comment by Ident** [comment]
- Complete Layout Editor (skinning editor was started in CEED but not completed)
- Automatic "packing" of image files into an imageset, so this does not need to be done manually anymore --> CEED has support for this already but lacks GUI for it
- Better scaling support for textures, right now there is only one image atlas but for 4k etc we might need more or we need mipmapping
- Vector graphics support  - this was started by allowing to manually draw them, but rasterization into images might be a more common approach and should be added, we can add nanovg for this
- Layout hot-reloading (might be a bit tricky considering references and runtime changes might be lost but we can think of an architecture here)
- Improve APIs, especially initialization, setup, etc. they are too complicated and error-prone. We need to think of ways to simplify them. Maybe we need to force users to call certain function else throw debug info, etc?
- Vulkan Renderer support
- Gamepad navigation support
- Animation editing must be easier
- Offer more animation effects
- Distance field rendering for displaying texts in the 3d world
- Unreal/Unity support
...

There is also some stuff in the wiki, todo's for me and mpreisler/kulik

**Comment by acxz** [comment]
I'll go ahead and close this issue, since it is not tracking anything specific.
