### ISSUE TITLE
Build error with uClibc/musl

### ISSUE THREAD

**Issue by bbilas** [cegui/cegui#1188]
Hello,
the build fails when uClibs/musl is being used.

```
/home/bartekk/Projects/buildroots/buildroot-dev/buildroot/output/build/cegui-0-8-7/cegui/src/Exceptions.cpp:45:25: fatal error: execinfo.h: No such file or directory
compilation terminated.
```

OS: Buildroot
GCC: 8.3.0

**Comment by Ident** [comment]
Can you suggest a fix or at least give more info? I have no idea about your setup

**Comment by bbilas** [comment]
I've created a PR #1189 which fixes above error.

**Comment by Ident** [comment]
Merged

**Comment by bbilas** [comment]
Is it possible to backport it into v0-8-7 version which is the latest stable version?

**Comment by Ident** [comment]
no, we would have to make a 0.8.8 release

**Comment by Ident** [comment]
you can fix it on v0-8 branch

**Comment by bbilas** [comment]
Sure, I'll wait for the 0.8.8 release then.

**Comment by bbilas** [comment]
Already done.
