### ISSUE TITLE
Override cmake options

### ISSUE THREAD

**Issue by bbilas** [cegui/cegui#1196]
Hi, I noticed that when the host contains i.e xerces already installed, but we don't wanna use it as xml parser, we are not able to force disable support for it. This also applies to other available options. I tried to do that via

`-DCEGUI_BUILD_XMLPARSER_XERCES=OFF`

but despite this xerces parser is being build. Do you have any idea how to solve that?

**Comment by Ident** [comment]
platform? the cegui option for xerces xml parser should turn it off via cmake

**Comment by bbilas** [comment]
I figured out that I had typos in my scripts therefore it didn't work... Sorry for the noise.
