### ISSUE TITLE
Cloning DragContainer causes crash

### ISSUE THREAD

**Issue by dhitchen** [cegui/cegui#1209]
When cloning the DragContainer it tries to set the DragIndicatorImage property which triggers an event which requires the GUIContext which has not yet been set.

**Comment by dhitchen** [comment]
https://github.com/cegui/cegui/pull/1211

**Comment by dhitchen** [comment]
Good chance I am not doing something right but I cant see a way of linking the pull request to the issue.

**Comment by dhitchen** [comment]
?

**Comment by niello** [comment]
I see the PR is already merged. Please reopen an issue if problem persists.
