### ISSUE TITLE
setting DEBUG macro in installed headers

### ISSUE THREAD

**Issue by rpaciorek** [cegui/cegui#1248]
CEGUI define `DEBUG` macro in installed `CEGUI/Config.h` (without any warning and even don't use it to anything important on use time). This can interference with other libs headers (e.g. Ogre) and cause weird error on runtime (e.g. different offset of class fields).

Suggested fix: do not manipulate `DEBUG` macro in installed headers.

**Comment by vorlov-playrix** [comment]
I will look at this a bit later
