### ISSUE TITLE
CGUIERROR std

### ISSUE THREAD

**Issue by TannicArcher** [cegui/cegui#1279]
![image](https://user-images.githubusercontent.com/113786861/216371639-9f18d249-7d4f-4520-b871-3c6ea641b6c4.png)
How to fix it
`	{
		using namespace std;

		if (d_cplength < idx)
			CEGUI_THROW(out_of_range("Index was out of range for CEGUI::String object"));

		size_type	maxlen = d_cplength - idx;

		return encoded_size(&ptr()[idx], ceguimin(num, maxlen));
	}`

**Comment by WeeKwok** [comment]
You need to include the header file where the declaration of std::min is located, but normally, cegui should already include the header file it needs, maybe you can try including CEGUI/CEGUI.h

**Comment by TannicArcher** [comment]
Thanks i fix it
