### ISSUE TITLE
Crash in Combo-box if it is expanded and you hide/remove screen by ESC (GUI context is null)

### ISSUE THREAD

**Issue by filip-martinko** [cegui/cegui#1298]
Steps:
1. run the sample browser
2. chose WidgetSample
3. change skin to TaharezLook
4. select Combobox in WidgetSelector
5. expand the combobox (drop list is showed)
6.  press 2x ESC

![image](https://github.com/cegui/cegui/assets/64005044/1d9594b3-bf90-4ad5-b488-6eb914f65bff)

So if you remove root and children elements and combobox is expanded then it crashes.

Here is the callstack in my program:
 	CEGUIBase-9999_d.dll!CEGUI::Window::getGUIContext() Line 3049	C++
 	CEGUIBase-9999_d.dll!CEGUI::Combobox::onDroplistRemoved(CEGUI8::WindowEventArgs & e) Line 452	C++
 	CEGUIBase-9999_d.dll!CEGUI::Combobox::droplist_HiddenHandler(const CEGUI8::EventArgs & __formal) Line 580	C++
 	CEGUIBase-9999_d.dll!CEGUI::MemberFunctionSlot<CEGUI8::Combobox>::operator()(const CEGUI8::EventArgs & args) Line 55	C++
 	CEGUIBase-9999_d.dll!CEGUI::SubscriberSlot::operator()(const CEGUI8::EventArgs & args) Line 113	C++
 	CEGUIBase-9999_d.dll!CEGUI::Event::operator()(CEGUI8::EventArgs & args) Line 92	C++
 	CEGUIBase-9999_d.dll!CEGUI::EventSet::fireEvent_impl(const CEGUI8::String & name, CEGUI8::EventArgs & args) Line 143	C++
 	CEGUIBase-9999_d.dll!CEGUI::EventSet::fireEvent(const CEGUI8::String & name, CEGUI8::EventArgs & args, const CEGUI8::String & eventNamespace) Line 125	C++
 	CEGUIBase-9999_d.dll!CEGUI::Window::onHidden(CEGUI8::WindowEventArgs & e) Line 1926	C++
 	CEGUIBase-9999_d.dll!CEGUI::Window::changeVisibility(bool setting) Line 717	C++
 	CEGUIBase-9999_d.dll!CEGUI::Window::setVisible(bool setting, bool force) Line 697	C++
 	CEGUIBase-9999_d.dll!CEGUI::Window::hide(bool force) Line 1408	C++
 	CEGUIBase-9999_d.dll!CEGUI::ComboDropList::onCaptureLost(CEGUI8::WindowEventArgs & e) Line 187	C++
 	CEGUIBase-9999_d.dll!CEGUI::GUIContext::releaseInputCapture(bool allowRestoreOld, CEGUI8::Window * exactWindow) Line 245	C++
 	CEGUIBase-9999_d.dll!CEGUI::GUIContext::setActiveWindow(CEGUI8::Window * window, bool moveToFront) Line 133	C++
 	CEGUIBase-9999_d.dll!CEGUI::GUIContext::onWindowDetached(CEGUI8::Window * window) Line 414	C++
 	CEGUIBase-9999_d.dll!CEGUI::Window::setGUIContextRecursively(CEGUI8::GUIContext * context) Line 3063	C++
 	CEGUIBase-9999_d.dll!CEGUI::Window::setGUIContextRecursively(CEGUI8::GUIContext * context) Line 3066	C++
 	CEGUIBase-9999_d.dll!CEGUI::Window::setGUIContextRecursively(CEGUI8::GUIContext * context) Line 3066	C++
 	CEGUIBase-9999_d.dll!CEGUI::Window::setGUIContextRecursively(CEGUI8::GUIContext * context) Line 3066	C++
 	CEGUIBase-9999_d.dll!CEGUI::Window::setGUIContextRecursively(CEGUI8::GUIContext * context) Line 3066	C++
 	CEGUIBase-9999_d.dll!CEGUI::Window::attachToGUIContext(CEGUI8::GUIContext * context) Line 3078	C++
 	CEGUIBase-9999_d.dll!CEGUI::Window::removeChild_impl(CEGUI8::Element * element) Line 1366	C++
 	CEGUIBase-9999_d.dll!CEGUI::Element::removeChild(CEGUI8::Element * element) Line 731	C++
>	GUI.dll!GUIMgr::hideScreen(GUI8Screen & screen) Line 488	C++

**Comment by FluXy** [comment]
Seems this can be closed now.
Also tested it with a different layout and doesn't crash.

**Comment by Ident** [comment]
Closed as per comment by @FluXy
