### ISSUE TITLE
Tolua throws error on equal op between userdatas

### ISSUE THREAD

**Issue by Ident** [cegui/cegui#373]
**[Original report](https://bitbucket.org/cegui/cegui/issue/373) by Paul Turner (Bitbucket: [pturner](https://bitbucket.org/pturner), GitHub: [pturner](https://github.com/pturner)).**

----------------------------------------

Seems like we maybe need to update the tolua++ version we're embedding.

See: http://www.cegui.org.uk/phpBB2/viewtopic.php?f=2&t=4932

**Reproducibility:** have not tried

**Comment by niello** [comment]
Won't fix. Too old and tolua++ is deprecated.
