### ISSUE TITLE
Tooltip error between windows

### ISSUE THREAD

**Issue by Ident** [cegui/cegui#38]
**[Original report](https://bitbucket.org/cegui/cegui/issue/38) by Anonymous.**

----------------------------------------

**Automatic migration. Original reporter: "Van"**

<b>Version:</b> 0.4.1 (from CVS as of today)
<b>Module:</b> CEGUIWindow.cpp 
<b>Function:</b> const String& Window::getTooltipText(void) const
<b>Line:</b> 3160
<bRendering System:</b> Ogre Dagon

This error usually occurs when a window has been deleted and another window is being created. Doesn't always do it, but I can reproduced 1/2 the time.

**Reproducibility:** sometimes

**Additional information:** <b>Error:</b>
Unhandled exception at 0x00adab76 (CEGUIBase_d.dll) in Client.exe: 0xC0000005: Access violation reading location 0x00000219.

<b>Instruction</b> (Line 3160)
if ( d_inheritsTipText && d_parent && d_tooltipText.empty() )

<b>Call Stack</b>
CEGUIBase_d.dll!CEGUI::Window::getTooltipText()  Line 3160 + 0x3	C++
CEGUIBase_d.dll!CEGUI::Tooltip::doInactiveState(float elapsed=2.1370001)  Line 224 + 0x1a	C++
CEGUIBase_d.dll!CEGUI::Tooltip::updateSelf(float elapsed=2.1370001)  Line 324	C++
CEGUIBase_d.dll!CEGUI::Window::update(float elapsed=2.1370001)  Line 2973 + 0x14	C++
CEGUIBase_d.dll!CEGUI::Window::update(float elapsed=2.1370001)  Line 2981	C++
CEGUIBase_d.dll!CEGUI::System::injectTimePulse(float timeElapsed=2.1370001)  Line 1101	C++
Client.exe!clsEventManager::frameEnded(const Ogre::FrameEvent & evt={...})  Line 77 + 0x2f	C++

**Comment by niello** [comment]
Too old, probably fixed long ago
