### ISSUE TITLE
LayoutContainers should relayout when their parent changes

### ISSUE THREAD

**Issue by Ident** [cegui/cegui#464]
**[Original report](https://bitbucket.org/cegui/cegui/issue/464) by Martin Preisler (Bitbucket: [mpreisler](https://bitbucket.org/mpreisler), GitHub: [mpreisler](https://github.com/mpreisler)).**

----------------------------------------

Since layout containers use their parent's size to relatively size their children, they definitely should mark themselves to relayout when their parent changes.

**Reproducibility:** always

**Steps to reproduce:** Create 2 windows (different sizes), 1 vertical layout container and add something to the layout container that is sized relatively.

Now try to remove the LC from first window and add it to the second. The children of the LC won't get resized.

**Comment by niello** [comment]
Was fixed
