### ISSUE TITLE
Elems created out of viewport then slided, are not clickable

### ISSUE THREAD

**Issue by Ident** [cegui/cegui#764]
**[Original report](https://bitbucket.org/cegui/cegui/issue/764) by Martin Preisler (Bitbucket: [mpreisler](https://bitbucket.org/mpreisler), GitHub: [mpreisler](https://github.com/mpreisler)).**

----------------------------------------

http://cegui.org.uk/phpBB2/viewtopic.php?f=10&t=6040

Thanks goes to matt for reporting!

**Reproducibility:** have not tried

**Comment by niello** [comment]
Seems to work. Too old to reproduce excatly.
