### ISSUE TITLE
Add GUIContext Update Event that uses UpdateEventArgs

### ISSUE THREAD

**Issue by Ident** [cegui/cegui#869]
**[Original report](https://bitbucket.org/cegui/cegui/issue/869) by Lukas Meindl (Bitbucket: [Ident8](https://bitbucket.org/Ident8), ).**

----------------------------------------

It would be useful if GUIContexts fire UpdateEvents for some users maybe (and for scripting?)

**Reproducibility:** N/A

**Comment by niello** [comment]
GUI ctx is a rendering surface, it has no 'update'. I would say the user must subscribe on the root window updates. Also this task is 9 years old.
