### ISSUE TITLE
Autoscaling of windows does not work correctly in some cases

### ISSUE THREAD

**Issue by Ident** [cegui/cegui#903]
**[Original report](https://bitbucket.org/cegui/cegui/issue/903) by Lukas Meindl (Bitbucket: [Ident8](https://bitbucket.org/Ident8), ).**

----------------------------------------

Example:
Window is sized to relative size of 1.0  vertically and horizontally, has an aspect ratio applied and is set to AM_EXPAND

On parent window resize the window is sometimes not expanded correctly and doesnt fully cover the screen

**Reproducibility:** always

**Steps to reproduce:** 1. start samplebrowser
2. open HUDDemo
3. make the application window to have very small width
4. see how the height isnt fully occluded

**Comment by niello** [comment]
Not reproduced, works as expected.
