### ISSUE TITLE
Lua 5.2.1 support -> tolua++cegui -> lua scripts

### ISSUE THREAD

**Issue by Ident** [cegui/cegui#918]
**[Original report](https://bitbucket.org/cegui/cegui/issue/918) by Anonymous.**

----------------------------------------

**Automatic migration. Original reporter: "DEvil HUnter"**

i'm now using lua 5.2.1 so i wanted tolua++/tolua++cegui to work with the same version of lua.
i wrote some compatibility fixes (see attachments).
one of the patches is maybe only because i use windows or some other thing not related to lua 5.2 but i included it seperate so you can include it if it is needed on your side too.

IMPORTANT!!! READ THIS!

normal tolua++ lua files (directly from tolua site) differes from the cegui tolua files. they support template classes and auto parsing of header files to "generate packages". you should merge their stuff to your tolua++cegui so we can directly use this. and you could also use the header to package parsing stuff and don't need to manually write the package files.
it uses magic in code comments for parsing and you just need to write 
$hfile "header.h"
in your package.

**Reproducibility:** N/A

**Comment by niello** [comment]
Won't fix. Too old, tolua++ is deprecated.
