### ISSUE TITLE
pressing tab - editbox

### ISSUE THREAD

**Issue by Ident** [cegui/cegui#920]
**[Original report](https://bitbucket.org/cegui/cegui/issue/920) by Anonymous.**

----------------------------------------

**Automatic migration. Original reporter: "DEvil HUnter"**

i would expect a editbox to verify input on pressing tab and focus next element (verify and focus last element shift+tab). but only on this combinations.
at the moment cegui editboxes will fire onTextAcceptedEvent() also on alt+tab what is realy not expected and bad.

**Reproducibility:** N/A

**Comment by niello** [comment]
Not reproduced. Only 'Enter' accepts the editbox text now (SemanticValue::Confirm)
