### ISSUE TITLE
Use of TinyXML parser module can cause 'unknown element' exceptions.

### ISSUE THREAD

**Issue by Ident** [cegui/cegui#928]
**[Original report](https://bitbucket.org/cegui/cegui/issue/928) by Paul Turner (Bitbucket: [pturner](https://bitbucket.org/pturner), GitHub: [pturner](https://github.com/pturner)).**

----------------------------------------

This issue was raised by the orxonox devs (http://www.orxonox.net/). I have confirmed the issue as described and reproduce parts of the initial email I received to save typing ;)

"I'm Johannes Ritz, a developer of the open source game Orxonox. We use CEGUI to create our user interface. Since the previous Ubuntu (12.04) release a problem occured related to the cegui package libcegui-mk2-dev (0.7.5-8)
http://packages.ubuntu.com/precise/libdevel/libcegui-mk2-dev (and the libcegui-mk2-0.7.5<http://packages.ubuntu.com/precise/libcegui-mk2-0.7.5>).

Our project compiles properly (after adding the packages libtolua-dev and libtolua++5.1-dev to our dependencies), but we receive a runtime error concerning tinyXML and CEGUI:

Error (internal): [cegui] Scheme_xmlHandler::elementStart: Unknown element encountered: <?>
"

**Reproducibility:** always

**Additional information:** Switching to the Expat based parser resolves this issue, so rules out issues with the datafiles and indicates some tinyxml specific issue - either with the parser lib itself, or the way that cegui is using it.

**Comment by niello** [comment]
TinyXML is obsolete and will be removed. Use TinyXML2 instead.
