### ISSUE TITLE
ItemListbox redraw problem

### ISSUE THREAD

**Issue by Ident** [cegui/cegui#933]
**[Original report](https://bitbucket.org/cegui/cegui/issue/933) by Pavlos Touboulidis (Bitbucket: [pavlos256](https://bitbucket.org/pavlos256), GitHub: [pavlos256](https://github.com/pavlos256)).**

----------------------------------------

The ItemListbox does not redraw itself on some cases, like when adding a new item. I haven't been able to find exactly what causes it: adding an item may or may not cause it to redraw!

**Reproducibility:** always

**Additional information:** Originally reported on the forum, here: http://www.cegui.org.uk/phpBB2/viewtopic.php?f=3&t=6220

Using the Ogre renderer, resizing the window (by dragging its border) is the only way to make it redraw and show the items.

**OS:** Linux, **OS build:** Arch, **Platform:** x86_64

**Comment by niello** [comment]
Probably fixed, noticed nothing like this when working on area changing code
