### ISSUE TITLE
Make TabControl::getButtonForTabContents public

### ISSUE THREAD

**Issue by Ident** [cegui/cegui#934]
**[Original report](https://bitbucket.org/cegui/cegui/issue/934) by Pavlos Touboulidis (Bitbucket: [pavlos256](https://bitbucket.org/pavlos256), GitHub: [pavlos256](https://github.com/pavlos256)).**

----------------------------------------

TabControl::getButtonForTabContents(Window* wnd) should be made public.

I'd like to get the tab button associated with a contents window to change it's 
properties but I can't, I have to duplicate that method's code.

**Reproducibility:** N/A

**Comment by niello** [comment]
Already public
