### ISSUE TITLE
A Koneki pack, to use CEGUI in pure Lua

### ISSUE THREAD

**Issue by Ident** [cegui/cegui#961]
**[Original report](https://bitbucket.org/cegui/cegui/issue/961) by Anonymous.**

----------------------------------------

**Automatic migration. Original reporter: "mattekenpis"**

Koneki (http://www.eclipse.org/koneki/ldt/) is an Eclipse tweak that provides a very nice IDE to write, run and debug Lua code.

It would be very nice to have a CEGUI "Execution Environments" for Koneki (as well as the tolua++ bindings were very very usefull), that would made available the use of CEGUI inside Eclipse, with pure Lua code. 

**Reproducibility:** have not tried

**Comment by niello** [comment]
Koneki was archived in 2015
