### ISSUE TITLE
WindowsLook Scrollablepane has its Verticalscrollbar wrongly rendered

### ISSUE THREAD

**Issue by Ident** [cegui/cegui#966]
**[Original report](https://bitbucket.org/cegui/cegui/issue/966) by Lukas Meindl (Bitbucket: [Ident8](https://bitbucket.org/Ident8), ).**

----------------------------------------

**Reproducibility:** always

**Steps to reproduce:** 1. Create a layout with a Root and a WindowsLook/ScrollablePane attached
2. Set ForceVertScrollbar on true
3. Dont add something to the scrollablepane that would actually require it to need a vertical scrollbar
4. THe resulting scrollbar should be rendered with only the top arrow shown, the thumb being about twice its supposed size and being clipped by the windows bottom, the bottom scrollbar arrow isnt shown at all

**OS:** Windows 7, **OS build:** , **Platform:** Windows 7

**Comment by niello** [comment]
Not reproduced
