### ISSUE TITLE
GUILayout_xmlHandler: child window properties from GUILayout not set when child window is added to parent

### ISSUE THREAD

**Issue by Ident** [cegui/cegui#972]
**[Original report](https://bitbucket.org/cegui/cegui/issue/972) by Anonymous.**

----------------------------------------

**Automatic migration. Original reporter: "marvinx"**

For the problem report and a possible fix, see http://www.cegui.org.uk/phpBB2/viewtopic.php?f=3&t=6424 .

When loading a GUILayout in CEGUI-0.7.7, the GUILayout_xmlHandler will add a child window to its parent BEFORE assigning it's properties from GUILayout. This will cause problems when one or more child window properties are used as conditions within the parent's addChild_impl(). For example, an overloaded addChild_impl() method of a custom ScrollablePane widget may rely on the "NonClient" property of the 'wnd' argument in order to decide if the new child is added to the ScrollContainer (as content window, NonClient=False), or if it becomes a child of the ScrollablePane itself (overlay window, NonClient=true).

**Reproducibility:** always

**Steps to reproduce:** For code and layout snippets that reproduce the reported problem, see http://www.cegui.org.uk/phpBB2/viewtopic.php?f=3&t=6424 .

**Additional information:** For a possible workaround, see http://www.cegui.org.uk/phpBB2/viewtopic.php?f=3&t=6424 .

**Comment by niello** [comment]
Won't fix. Was needed for the very specific case that has different solutions.
