### ISSUE TITLE
Suggestion for smarter CEGUIWindow::getHitTestRect_impl

### ISSUE THREAD

**Issue by Ident** [cegui/cegui#973]
**[Original report](https://bitbucket.org/cegui/cegui/issue/973) by Anonymous.**

----------------------------------------

**Automatic migration. Original reporter: "marvinx"**

See discussion from http://www.cegui.org.uk/phpBB2/viewtopic.php?f=3&t=6429

**Reproducibility:** always

**Steps to reproduce:** See http://www.cegui.org.uk/phpBB2/viewtopic.php?f=3&t=6429

**Additional information:** ".. ideally "the non-clipped by parent child" with a texture backed parent should actually render outside of the parent's texture." But what if the the parent itself is rendered to texture and not to screen? The current getHitTestRect_impl() does not deal with such window configurations.

**Comment by niello** [comment]
Won't fix. This was a subject for discussion, not a task ready for impl. It looks not actual.
