### ISSUE TITLE
virtual CEGUIRenderingWindow::unprojectPoint_impl

### ISSUE THREAD

**Issue by Ident** [cegui/cegui#974]
**[Original report](https://bitbucket.org/cegui/cegui/issue/974) by Anonymous.**

----------------------------------------

**Automatic migration. Original reporter: "marvinx"**

In some cases it may be necessary to completely override or extend the default implementation from CEGUI::RenderingWindow::unprojectPoint(). At the moment there is no such virtual "stub" available for CEGUIRenderingWindow extensions.  

**Reproducibility:** N/A

**Comment by niello** [comment]
Too old and not demanded by users
