### ISSUE TITLE
Floating point divide-by-zero in CEGUI::FalagardScrollbar::updateThumb()

### ISSUE THREAD

**Issue by Ident** [cegui/cegui#975]
**[Original report](https://bitbucket.org/cegui/cegui/issue/975) by Anonymous.**

----------------------------------------

**Automatic migration. Original reporter: "Muon"**

There appear to be some floating point division-by-zero issues. While this is ordinarily non-fatal, it produces infinities, or if it's 0./0., NaNs. I've detected these since I run my program with some FPU flags set to signaling.

**Reproducibility:** always

**Steps to reproduce:** Turn FPU exceptions on and create anything that can have a scrollbar, but doesn't need one. The dimensions will be set to zero, and the program will terminate with a floating point exception.

**Additional information:** Example .layout that causes crash: http://pastie.org/private/z5mnhf0vrcxlhmwy2yq5w
Backtrace: http://pastie.org/private/l42ighzhqmxdo806bd7e9g

**Comment by niello** [comment]
Already fixed
