### ISSUE TITLE
Internal check for GL vs GL3 renderer using identifier string

### ISSUE THREAD

**Issue by Ident** [cegui/cegui#981]
**[Original report](https://bitbucket.org/cegui/cegui/issue/981) by Paul Turner (Bitbucket: [pturner](https://bitbucket.org/pturner), GitHub: [pturner](https://github.com/pturner)).**

----------------------------------------

We have a check in Texture.cpp that ensures it does not call functions not available in 3.2+ core profile when running under GL3 renderer, but does call them under regular GL renderer (where they are required). This was added to fix #980.

Currently, the check is doing a string comparison - a technique required in order to maintain ABI on the v0-8 branch. However, ideally for other branches, we would use something better, such as a virtual function or what have you.

**Reproducibility:** N/A

**Comment by niello** [comment]
`OpenGLTexture::setTextureEnvironment()` was added for that
